[tasks.prepare-integration-test]
description = "Build cdylib for compiler integration test"
cwd = "../cdylib"
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "nodejs", "--out-dir", "../compiler-lib/tests/pkg"]

[tasks.prepare-integration-test-release]
description = "Build cdylib for compiler integration test (release)"
extend = "prepare-integration-test"
args = ["build", "--target", "nodejs", "--release", "--out-dir", "../compiler-lib/tests/pkg"]

[tasks.test]
description = "Run tests"
dependencies = [
    { name = "prepare-integration-test" }, 
    { name = "build-release", path = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/cdylib" }
]
command = "cargo"
args = ["test"]

[tasks.test-release]
description = "Run tests (release)"
dependencies = [
    { name = "prepare-integration-test-release" }, 
    { name = "build-release", path = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/cdylib" }
]
command = "cargo"
args = ["test", "--release"]

[tasks.clean-dylib]
description = "Clean rust artifacts"
command = "rm"
args = ["-rf", "./tests/pkg"]

[tasks.clean-asm]
script = '''
rm -rf ./tests/*.s
'''

[tasks.clean-rust]
description = "Clean rust artifacts"
command = "cargo"
args = ["clean"]

[tasks.clean]
description = "Clean"
dependencies = ["clean-dylib", "clean-rust", "clean-asm"]
