# name: CI
# on: [push, pull_request]

# jobs:
#   test:
#     name: test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Install Rust toolchain
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#           profile: minimal

#       - name: Cache cargo dir
#         uses: Swatinem/rust-cache@v1
#         with:
#           working-directory: ./tiger

#       - name: Rustfmt
#         uses: actions-rs/cargo@v1
#         with:
#           command: fmt
#           args: --manifest-path ./tiger/Cargo.toml --all -- --check

#       - name: Clippy
#         uses: actions-rs/cargo@v1
#         with:
#           command: clippy
#           args: --manifest-path ./tiger/Cargo.toml

#       - name: Test
#         uses: actions-rs/cargo@v1
#         with:
#           command: test
#           args: --manifest-path ./tiger/Cargo.toml
