name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack

      - name: Cache cargo dir
        uses: Swatinem/rust-cache@v2

      - name: Build for wasm
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release
