[tasks.build]
description = "Build the web app"
cwd = "./web"
dependencies = ["build_cdylib", "build_compiler"]
command = "npm"
args = ["run", "build"]

[tasks.build_cdylib]
description = "Build the cdylib"
cwd = "../cdylib"
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "web", "--release", "--out-dir", "../web/web/src/pkg_cdylib"]

[tasks.build_compiler]
description = "Build the compiler"
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "web", "--release", "--out-dir", "./web/src/pkg_compiler"]

